#!/bin/sh
### BEGIN INIT INFO
# Provides:          nova-umbrella
# Required-Start:    $network $local_fs $remote_fs $syslog
# Required-Stop:     $remote_fs
# Default-Start:     2 4 5
# Default-Stop:      0 1 3 6
# Short-Description: Nova umbrella
# Description:
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/user/local/bin
DESC="OpenStack umbrella"
NAME=umbrella-api
DAEMON=/usr/bin/umbrella-api
DAEMON_ARGS="--config-file=/etc/umbrella/umbrella-api.conf"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
UMBRELLA_USER=root
LOCK_DIR=/var/lock/umbrella/
DEFAULTS_FILE=/etc/default/umbrella-common

# Exit if the package is not installed
[ -x $DAEMON ] || exit 0

mkdir -p ${LOCK_DIR}
chown ${UMBRELLA_USER} ${LOCK_DIR}

. /lib/lsb/init-functions

test -f '/etc/umbrella/umbrella-pass.conf' && DAEMON_ARGS=${DAEMON_ARGS}" --config-file=/etc/umbrella/umbrella-pass.conf"

# Read configuration variable file if it is present
if [ -s $DEFAULTS_FILE ]; then
    . $DEFAULTS_FILE
    case "x$UMBRELLA_ENABLE" in
        xtrue|xfalse)   ;;
        *)              log_failure_msg "Value of UMBRELLA_ENABLE in $DEFAULTS_FILE must be either 'true' or 'false';"
                        log_failure_msg "not starting $NAME daemon."
                        exit 1
                        ;;
    esac
fi


do_start()
{
    # Check if the ULIMIT is set in /etc/default/umbrella-common
    if [ -n "$ULIMIT" ]; then
        # Set the ulimits
        ulimit -n $ULIMIT
    fi
	start-stop-daemon --start --quiet --background --chuid ${UMBRELLA_USER}:${UMBRELLA_USER} --make-pidfile --pidfile $PIDFILE --startas $DAEMON --test > /dev/null \
		|| return 1
	start-stop-daemon --start --quiet --background --chuid ${UMBRELLA_USER}:${UMBRELLA_USER} --make-pidfile --pidfile $PIDFILE --startas $DAEMON -- \
		$DAEMON_ARGS \
		|| return 2
}

do_stop()
{
	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
	RETVAL="$?"
	rm -f $PIDFILE
	return "$RETVAL"
}

case "$1" in
  start)
        if "$UMBRELLA_ENABLE"; then
            log_daemon_msg "Starting $DESC" "$NAME"
            do_start
            case "$?" in
                0|1) log_end_msg 0 ;;
                2) log_end_msg 1 ;;
            esac
        else
            log_warning_msg "umbrella daemons not enabled in $DEFAULTS_FILE, not starting..."
        fi
        ;;
  stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) log_end_msg 0 ;;
		2) log_end_msg 1 ;;
	esac
	;;
  status)
       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
       ;;
  restart|force-reload)
        if "$UMBRELLA_ENABLE"; then
            log_daemon_msg "Restarting $DESC" "$NAME"
            do_stop
            case "$?" in
                0|1)
                    do_start
                    case "$?" in
                        0) log_end_msg 0 ;;
                        1) log_end_msg 1 ;; # Old process is still running
                        *) log_end_msg 1 ;; # Failed to start
                    esac
                    ;;
                *)
                # Failed to stop
                    log_end_msg 1
                    ;;
            esac
        else
            log_warning_msg "umbrella daemons not enabled in $DEFAULTS_FILE, not starting..."
        fi
        ;;

  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

